### ISSUE TITLE
Please update to latest version 1.4.4.1

### ISSUE THREAD

**Issue by shaguarger** [hexlo/terraria-server-docker#4]
New version is there with fix for the broken startup crash on Linux:
https://forums.terraria.org/index.php?threads/startup-crash-on-linux-version-1-4-4.114699/

[Terraria Server 1.4.4.1](https://terraria.org/api/download/pc-dedicated-server/terraria-server-1441.zip)

Thx :)

**Comment by heinermann** [comment]
I have the exact same error. It happens when someone attempts to join the game, then it crashes and reboots (with that error specifically).

I'm using 1.4.4.2.

There is a link that doesn't really match the format this docker container is expecting: https://terraria.org/api/download/pc-dedicated-server/terraria-server-1441-fixed.zip

The one we probably want isn't in the wiki pointed to in [this script](https://github.com/hexlo/terraria-server-docker/blob/main/.scripts/get-terraria-version.sh): https://terraria.org/api/download/pc-dedicated-server/terraria-server-1442.zip

**Comment by hexlo** [comment]
It is now updated to 1.4.4.2. Let me know if there's any other issues!

**Comment by heinermann** [comment]
Thanks, it's working now.
